// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOcWQx3aXLQWD2WNlcC1e9OGERiYQKjYk',
    appId: '1:244279615989:web:68f06400c3392a143ac0bc',
    messagingSenderId: '244279615989',
    projectId: 'flutteradvanced-4c408',
    authDomain: 'flutteradvanced-4c408.firebaseapp.com',
    storageBucket: 'flutteradvanced-4c408.appspot.com',
    measurementId: 'G-8VT1SF3GJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxmM2O3maJlXCzm_yluFg0Hhm4oOA_vw',
    appId: '1:244279615989:android:b865ea5679d9e2033ac0bc',
    messagingSenderId: '244279615989',
    projectId: 'flutteradvanced-4c408',
    storageBucket: 'flutteradvanced-4c408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFlg9zEhTgawmoP4qjBuvwbKKCPvScv0',
    appId: '1:244279615989:ios:eb80fdd67c0392f03ac0bc',
    messagingSenderId: '244279615989',
    projectId: 'flutteradvanced-4c408',
    storageBucket: 'flutteradvanced-4c408.appspot.com',
    iosBundleId: 'com.example.flutterAdvance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWFlg9zEhTgawmoP4qjBuvwbKKCPvScv0',
    appId: '1:244279615989:ios:eb80fdd67c0392f03ac0bc',
    messagingSenderId: '244279615989',
    projectId: 'flutteradvanced-4c408',
    storageBucket: 'flutteradvanced-4c408.appspot.com',
    iosBundleId: 'com.example.flutterAdvance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOcWQx3aXLQWD2WNlcC1e9OGERiYQKjYk',
    appId: '1:244279615989:web:92b8e3af110f540a3ac0bc',
    messagingSenderId: '244279615989',
    projectId: 'flutteradvanced-4c408',
    authDomain: 'flutteradvanced-4c408.firebaseapp.com',
    storageBucket: 'flutteradvanced-4c408.appspot.com',
    measurementId: 'G-XG13G6RFPH',
  );
}
